stages:
  - lint
  - build

lint-client:
  stage: lint
  image: node:22
  script:
    - cd client
    - npm ci
    - npm run lint

lint-server:
  stage: lint
  image: node:22
  script:
    - cd server
    - npm ci
    - npm run lint

build-client:
  stage: build
  image: node:22
  script:
    - cd client
    - npm ci
    - npm run build

build-server:
  stage: build
  image: node:22
  script:
    - cd server
    - npm ci
    - npm run build